<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_dt.proto

namespace Basho\Riak\Api\Pb\Message\MapUpdate;

use UnexpectedValueException;

/**
 * Flags only exist inside Maps and can only be enabled or
 * disabled, and there are no arguments to the operations.
 *
 * Protobuf type <code>MapUpdate.FlagOp</code>
 */
class FlagOp
{
    /**
     * Generated from protobuf enum <code>ENABLE = 0;</code>
     */
    const ENABLE = 0;
    /**
     * Generated from protobuf enum <code>DISABLE = 1;</code>
     */
    const DISABLE = 1;

    private static $valueToName = [
        self::ENABLE => 'ENABLE',
        self::DISABLE => 'DISABLE',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(FlagOp::class, \Basho\Riak\Api\Pb\Message\MapUpdate_FlagOp::class);

