<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message\RpbIndexReq;

use UnexpectedValueException;

/**
 * Protobuf type <code>RpbIndexReq.IndexQueryType</code>
 */
class IndexQueryType
{
    /**
     * Generated from protobuf enum <code>eq = 0;</code>
     */
    const eq = 0;
    /**
     * Generated from protobuf enum <code>range = 1;</code>
     */
    const range = 1;

    private static $valueToName = [
        self::eq => 'eq',
        self::range => 'range',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

// Adding a class alias for backwards compatibility with the previous class name.
class_alias(IndexQueryType::class, \Basho\Riak\Api\Pb\Message\RpbIndexReq_IndexQueryType::class);

