<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_dt.proto

namespace Basho\Riak\Api\Pb\Message;

if (false) {
    /**
     * This class is deprecated. Use Basho\Riak\Api\Pb\Message\DtFetchResp\DataType instead.
     * @deprecated
     */
    class DtFetchResp_DataType {}
}
class_exists(DtFetchResp\DataType::class);
@trigger_error('Basho\Riak\Api\Pb\Message\DtFetchResp_DataType is deprecated and will be removed in the next major release. Use Basho\Riak\Api\Pb\Message\DtFetchResp\DataType instead', E_USER_DEPRECATED);

