<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_dt.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An entry in a map is a pair of a field-name and value. The type
 * defined in the field determines which value type is expected.
 *
 * Generated from protobuf message <code>MapEntry</code>
 */
class MapEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.MapField field = 1;</code>
     */
    protected $field = null;
    /**
     * Generated from protobuf field <code>sint64 counter_value = 2;</code>
     */
    protected $counter_value = null;
    /**
     * Generated from protobuf field <code>repeated bytes set_value = 3;</code>
     */
    private $set_value;
    /**
     * Generated from protobuf field <code>bytes register_value = 4;</code>
     */
    protected $register_value = null;
    /**
     * Generated from protobuf field <code>bool flag_value = 5;</code>
     */
    protected $flag_value = null;
    /**
     * Generated from protobuf field <code>repeated .MapEntry map_value = 6;</code>
     */
    private $map_value;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\MapField $field
     *     @type int|string $counter_value
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $set_value
     *     @type string $register_value
     *     @type bool $flag_value
     *     @type \Basho\Riak\Api\Pb\Message\MapEntry[]|\Google\Protobuf\Internal\RepeatedField $map_value
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakDt::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.MapField field = 1;</code>
     * @return \Basho\Riak\Api\Pb\Message\MapField
     */
    public function getField()
    {
        return isset($this->field) ? $this->field : null;
    }

    public function hasField()
    {
        return isset($this->field);
    }

    public function clearField()
    {
        unset($this->field);
    }

    /**
     * Generated from protobuf field <code>.MapField field = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\MapField $var
     * @return $this
     */
    public function setField($var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\MapField::class);
        $this->field = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 counter_value = 2;</code>
     * @return int|string
     */
    public function getCounterValue()
    {
        return isset($this->counter_value) ? $this->counter_value : 0;
    }

    public function hasCounterValue()
    {
        return isset($this->counter_value);
    }

    public function clearCounterValue()
    {
        unset($this->counter_value);
    }

    /**
     * Generated from protobuf field <code>sint64 counter_value = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCounterValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->counter_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes set_value = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSetValue()
    {
        return $this->set_value;
    }

    /**
     * Generated from protobuf field <code>repeated bytes set_value = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSetValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->set_value = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes register_value = 4;</code>
     * @return string
     */
    public function getRegisterValue()
    {
        return isset($this->register_value) ? $this->register_value : '';
    }

    public function hasRegisterValue()
    {
        return isset($this->register_value);
    }

    public function clearRegisterValue()
    {
        unset($this->register_value);
    }

    /**
     * Generated from protobuf field <code>bytes register_value = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setRegisterValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->register_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool flag_value = 5;</code>
     * @return bool
     */
    public function getFlagValue()
    {
        return isset($this->flag_value) ? $this->flag_value : false;
    }

    public function hasFlagValue()
    {
        return isset($this->flag_value);
    }

    public function clearFlagValue()
    {
        unset($this->flag_value);
    }

    /**
     * Generated from protobuf field <code>bool flag_value = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setFlagValue($var)
    {
        GPBUtil::checkBool($var);
        $this->flag_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MapEntry map_value = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getMapValue()
    {
        return $this->map_value;
    }

    /**
     * Generated from protobuf field <code>repeated .MapEntry map_value = 6;</code>
     * @param \Basho\Riak\Api\Pb\Message\MapEntry[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setMapValue($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\MapEntry::class);
        $this->map_value = $arr;

        return $this;
    }

}

