<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_dt.proto

namespace Basho\Riak\Api\Pb\Message;

if (false) {
    /**
     * This class is deprecated. Use Basho\Riak\Api\Pb\Message\MapField\MapFieldType instead.
     * @deprecated
     */
    class MapField_MapFieldType {}
}
class_exists(MapField\MapFieldType::class);
@trigger_error('Basho\Riak\Api\Pb\Message\MapField_MapFieldType is deprecated and will be removed in the next major release. Use Basho\Riak\Api\Pb\Message\MapField\MapFieldType instead', E_USER_DEPRECATED);

