<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_dt.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An operation to update a Map. All operations apply to individual
 * fields in the Map.
 *
 * Generated from protobuf message <code>MapOp</code>
 */
class MapOp extends \Google\Protobuf\Internal\Message
{
    /**
     *  REMOVE removes a field and value from the Map.
     * UPDATE applies type-specific
     * operations to the values stored in the Map.
     *
     * Generated from protobuf field <code>repeated .MapField removes = 1;</code>
     */
    private $removes;
    /**
     * Generated from protobuf field <code>repeated .MapUpdate updates = 2;</code>
     */
    private $updates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\MapField[]|\Google\Protobuf\Internal\RepeatedField $removes
     *            REMOVE removes a field and value from the Map.
     *           UPDATE applies type-specific
     *           operations to the values stored in the Map.
     *     @type \Basho\Riak\Api\Pb\Message\MapUpdate[]|\Google\Protobuf\Internal\RepeatedField $updates
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakDt::initOnce();
        parent::__construct($data);
    }

    /**
     *  REMOVE removes a field and value from the Map.
     * UPDATE applies type-specific
     * operations to the values stored in the Map.
     *
     * Generated from protobuf field <code>repeated .MapField removes = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRemoves()
    {
        return $this->removes;
    }

    /**
     *  REMOVE removes a field and value from the Map.
     * UPDATE applies type-specific
     * operations to the values stored in the Map.
     *
     * Generated from protobuf field <code>repeated .MapField removes = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\MapField[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRemoves($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\MapField::class);
        $this->removes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .MapUpdate updates = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUpdates()
    {
        return $this->updates;
    }

    /**
     * Generated from protobuf field <code>repeated .MapUpdate updates = 2;</code>
     * @param \Basho\Riak\Api\Pb\Message\MapUpdate[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUpdates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\MapUpdate::class);
        $this->updates = $arr;

        return $this;
    }

}

