<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_dt.proto

namespace Basho\Riak\Api\Pb\Message;

if (false) {
    /**
     * This class is deprecated. Use Basho\Riak\Api\Pb\Message\MapUpdate\FlagOp instead.
     * @deprecated
     */
    class MapUpdate_FlagOp {}
}
class_exists(MapUpdate\FlagOp::class);
@trigger_error('Basho\Riak\Api\Pb\Message\MapUpdate_FlagOp is deprecated and will be removed in the next major release. Use Basho\Riak\Api\Pb\Message\MapUpdate\FlagOp instead', E_USER_DEPRECATED);

