<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak.proto

namespace Basho\Riak\Api\Pb\Message;

if (false) {
    /**
     * This class is deprecated. Use Basho\Riak\Api\Pb\Message\RpbBucketProps\RpbReplMode instead.
     * @deprecated
     */
    class RpbBucketProps_RpbReplMode {}
}
class_exists(RpbBucketProps\RpbReplMode::class);
@trigger_error('Basho\Riak\Api\Pb\Message\RpbBucketProps_RpbReplMode is deprecated and will be removed in the next major release. Use Basho\Riak\Api\Pb\Message\RpbBucketProps\RpbReplMode instead', E_USER_DEPRECATED);

