<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Counter update request
 *
 * Generated from protobuf message <code>RpbCounterUpdateReq</code>
 */
class RpbCounterUpdateReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     */
    protected $bucket = '';
    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>sint64 amount = 3;</code>
     */
    protected $amount = 0;
    /**
     * Generated from protobuf field <code>uint32 w = 4;</code>
     */
    protected $w = null;
    /**
     * Generated from protobuf field <code>uint32 dw = 5;</code>
     */
    protected $dw = null;
    /**
     * Generated from protobuf field <code>uint32 pw = 6;</code>
     */
    protected $pw = null;
    /**
     * Generated from protobuf field <code>bool returnvalue = 7;</code>
     */
    protected $returnvalue = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bucket
     *     @type string $key
     *     @type int|string $amount
     *     @type int $w
     *     @type int $dw
     *     @type int $pw
     *     @type bool $returnvalue
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     * @return string
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 amount = 3;</code>
     * @return int|string
     */
    public function getAmount()
    {
        return $this->amount;
    }

    /**
     * Generated from protobuf field <code>sint64 amount = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAmount($var)
    {
        GPBUtil::checkInt64($var);
        $this->amount = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 w = 4;</code>
     * @return int
     */
    public function getW()
    {
        return isset($this->w) ? $this->w : 0;
    }

    public function hasW()
    {
        return isset($this->w);
    }

    public function clearW()
    {
        unset($this->w);
    }

    /**
     * Generated from protobuf field <code>uint32 w = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setW($var)
    {
        GPBUtil::checkUint32($var);
        $this->w = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 dw = 5;</code>
     * @return int
     */
    public function getDw()
    {
        return isset($this->dw) ? $this->dw : 0;
    }

    public function hasDw()
    {
        return isset($this->dw);
    }

    public function clearDw()
    {
        unset($this->dw);
    }

    /**
     * Generated from protobuf field <code>uint32 dw = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDw($var)
    {
        GPBUtil::checkUint32($var);
        $this->dw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 pw = 6;</code>
     * @return int
     */
    public function getPw()
    {
        return isset($this->pw) ? $this->pw : 0;
    }

    public function hasPw()
    {
        return isset($this->pw);
    }

    public function clearPw()
    {
        unset($this->pw);
    }

    /**
     * Generated from protobuf field <code>uint32 pw = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPw($var)
    {
        GPBUtil::checkUint32($var);
        $this->pw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool returnvalue = 7;</code>
     * @return bool
     */
    public function getReturnvalue()
    {
        return isset($this->returnvalue) ? $this->returnvalue : false;
    }

    public function hasReturnvalue()
    {
        return isset($this->returnvalue);
    }

    public function clearReturnvalue()
    {
        unset($this->returnvalue);
    }

    /**
     * Generated from protobuf field <code>bool returnvalue = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setReturnvalue($var)
    {
        GPBUtil::checkBool($var);
        $this->returnvalue = $var;

        return $this;
    }

}

