<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * counter value
 *
 * Generated from protobuf message <code>RpbCounterGetReq</code>
 */
class RpbCounterGetReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     */
    protected $bucket = '';
    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>uint32 r = 3;</code>
     */
    protected $r = null;
    /**
     * Generated from protobuf field <code>uint32 pr = 4;</code>
     */
    protected $pr = null;
    /**
     * Generated from protobuf field <code>bool basic_quorum = 5;</code>
     */
    protected $basic_quorum = null;
    /**
     * Generated from protobuf field <code>bool notfound_ok = 6;</code>
     */
    protected $notfound_ok = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bucket
     *     @type string $key
     *     @type int $r
     *     @type int $pr
     *     @type bool $basic_quorum
     *     @type bool $notfound_ok
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     * @return string
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 r = 3;</code>
     * @return int
     */
    public function getR()
    {
        return isset($this->r) ? $this->r : 0;
    }

    public function hasR()
    {
        return isset($this->r);
    }

    public function clearR()
    {
        unset($this->r);
    }

    /**
     * Generated from protobuf field <code>uint32 r = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setR($var)
    {
        GPBUtil::checkUint32($var);
        $this->r = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 pr = 4;</code>
     * @return int
     */
    public function getPr()
    {
        return isset($this->pr) ? $this->pr : 0;
    }

    public function hasPr()
    {
        return isset($this->pr);
    }

    public function clearPr()
    {
        unset($this->pr);
    }

    /**
     * Generated from protobuf field <code>uint32 pr = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPr($var)
    {
        GPBUtil::checkUint32($var);
        $this->pr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool basic_quorum = 5;</code>
     * @return bool
     */
    public function getBasicQuorum()
    {
        return isset($this->basic_quorum) ? $this->basic_quorum : false;
    }

    public function hasBasicQuorum()
    {
        return isset($this->basic_quorum);
    }

    public function clearBasicQuorum()
    {
        unset($this->basic_quorum);
    }

    /**
     * Generated from protobuf field <code>bool basic_quorum = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setBasicQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->basic_quorum = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool notfound_ok = 6;</code>
     * @return bool
     */
    public function getNotfoundOk()
    {
        return isset($this->notfound_ok) ? $this->notfound_ok : false;
    }

    public function hasNotfoundOk()
    {
        return isset($this->notfound_ok);
    }

    public function clearNotfoundOk()
    {
        unset($this->notfound_ok);
    }

    /**
     * Generated from protobuf field <code>bool notfound_ok = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setNotfoundOk($var)
    {
        GPBUtil::checkBool($var);
        $this->notfound_ok = $var;

        return $this;
    }

}

