<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Delete request
 *
 * Generated from protobuf message <code>RpbDelReq</code>
 */
class RpbDelReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     */
    protected $bucket = '';
    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>uint32 rw = 3;</code>
     */
    protected $rw = null;
    /**
     * Generated from protobuf field <code>bytes vclock = 4;</code>
     */
    protected $vclock = null;
    /**
     * Generated from protobuf field <code>uint32 r = 5;</code>
     */
    protected $r = null;
    /**
     * Generated from protobuf field <code>uint32 w = 6;</code>
     */
    protected $w = null;
    /**
     * Generated from protobuf field <code>uint32 pr = 7;</code>
     */
    protected $pr = null;
    /**
     * Generated from protobuf field <code>uint32 pw = 8;</code>
     */
    protected $pw = null;
    /**
     * Generated from protobuf field <code>uint32 dw = 9;</code>
     */
    protected $dw = null;
    /**
     * Generated from protobuf field <code>uint32 timeout = 10;</code>
     */
    protected $timeout = null;
    /**
     * Experimental, may change/disappear
     *
     * Generated from protobuf field <code>bool sloppy_quorum = 11;</code>
     */
    protected $sloppy_quorum = null;
    /**
     * Experimental, may change/disappear
     *
     * Generated from protobuf field <code>uint32 n_val = 12;</code>
     */
    protected $n_val = null;
    /**
     * Bucket type, if not set we assume the 'default' type
     *
     * Generated from protobuf field <code>bytes type = 13;</code>
     */
    protected $type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bucket
     *     @type string $key
     *     @type int $rw
     *     @type string $vclock
     *     @type int $r
     *     @type int $w
     *     @type int $pr
     *     @type int $pw
     *     @type int $dw
     *     @type int $timeout
     *     @type bool $sloppy_quorum
     *           Experimental, may change/disappear
     *     @type int $n_val
     *           Experimental, may change/disappear
     *     @type string $type
     *           Bucket type, if not set we assume the 'default' type
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     * @return string
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>bytes key = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 rw = 3;</code>
     * @return int
     */
    public function getRw()
    {
        return isset($this->rw) ? $this->rw : 0;
    }

    public function hasRw()
    {
        return isset($this->rw);
    }

    public function clearRw()
    {
        unset($this->rw);
    }

    /**
     * Generated from protobuf field <code>uint32 rw = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setRw($var)
    {
        GPBUtil::checkUint32($var);
        $this->rw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes vclock = 4;</code>
     * @return string
     */
    public function getVclock()
    {
        return isset($this->vclock) ? $this->vclock : '';
    }

    public function hasVclock()
    {
        return isset($this->vclock);
    }

    public function clearVclock()
    {
        unset($this->vclock);
    }

    /**
     * Generated from protobuf field <code>bytes vclock = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setVclock($var)
    {
        GPBUtil::checkString($var, False);
        $this->vclock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 r = 5;</code>
     * @return int
     */
    public function getR()
    {
        return isset($this->r) ? $this->r : 0;
    }

    public function hasR()
    {
        return isset($this->r);
    }

    public function clearR()
    {
        unset($this->r);
    }

    /**
     * Generated from protobuf field <code>uint32 r = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setR($var)
    {
        GPBUtil::checkUint32($var);
        $this->r = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 w = 6;</code>
     * @return int
     */
    public function getW()
    {
        return isset($this->w) ? $this->w : 0;
    }

    public function hasW()
    {
        return isset($this->w);
    }

    public function clearW()
    {
        unset($this->w);
    }

    /**
     * Generated from protobuf field <code>uint32 w = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setW($var)
    {
        GPBUtil::checkUint32($var);
        $this->w = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 pr = 7;</code>
     * @return int
     */
    public function getPr()
    {
        return isset($this->pr) ? $this->pr : 0;
    }

    public function hasPr()
    {
        return isset($this->pr);
    }

    public function clearPr()
    {
        unset($this->pr);
    }

    /**
     * Generated from protobuf field <code>uint32 pr = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPr($var)
    {
        GPBUtil::checkUint32($var);
        $this->pr = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 pw = 8;</code>
     * @return int
     */
    public function getPw()
    {
        return isset($this->pw) ? $this->pw : 0;
    }

    public function hasPw()
    {
        return isset($this->pw);
    }

    public function clearPw()
    {
        unset($this->pw);
    }

    /**
     * Generated from protobuf field <code>uint32 pw = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setPw($var)
    {
        GPBUtil::checkUint32($var);
        $this->pw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 dw = 9;</code>
     * @return int
     */
    public function getDw()
    {
        return isset($this->dw) ? $this->dw : 0;
    }

    public function hasDw()
    {
        return isset($this->dw);
    }

    public function clearDw()
    {
        unset($this->dw);
    }

    /**
     * Generated from protobuf field <code>uint32 dw = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setDw($var)
    {
        GPBUtil::checkUint32($var);
        $this->dw = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 10;</code>
     * @return int
     */
    public function getTimeout()
    {
        return isset($this->timeout) ? $this->timeout : 0;
    }

    public function hasTimeout()
    {
        return isset($this->timeout);
    }

    public function clearTimeout()
    {
        unset($this->timeout);
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkUint32($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Experimental, may change/disappear
     *
     * Generated from protobuf field <code>bool sloppy_quorum = 11;</code>
     * @return bool
     */
    public function getSloppyQuorum()
    {
        return isset($this->sloppy_quorum) ? $this->sloppy_quorum : false;
    }

    public function hasSloppyQuorum()
    {
        return isset($this->sloppy_quorum);
    }

    public function clearSloppyQuorum()
    {
        unset($this->sloppy_quorum);
    }

    /**
     * Experimental, may change/disappear
     *
     * Generated from protobuf field <code>bool sloppy_quorum = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setSloppyQuorum($var)
    {
        GPBUtil::checkBool($var);
        $this->sloppy_quorum = $var;

        return $this;
    }

    /**
     * Experimental, may change/disappear
     *
     * Generated from protobuf field <code>uint32 n_val = 12;</code>
     * @return int
     */
    public function getNVal()
    {
        return isset($this->n_val) ? $this->n_val : 0;
    }

    public function hasNVal()
    {
        return isset($this->n_val);
    }

    public function clearNVal()
    {
        unset($this->n_val);
    }

    /**
     * Experimental, may change/disappear
     *
     * Generated from protobuf field <code>uint32 n_val = 12;</code>
     * @param int $var
     * @return $this
     */
    public function setNVal($var)
    {
        GPBUtil::checkUint32($var);
        $this->n_val = $var;

        return $this;
    }

    /**
     * Bucket type, if not set we assume the 'default' type
     *
     * Generated from protobuf field <code>bytes type = 13;</code>
     * @return string
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : '';
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Bucket type, if not set we assume the 'default' type
     *
     * Generated from protobuf field <code>bytes type = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;

        return $this;
    }

}

