<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Get bucket properties response
 *
 * Generated from protobuf message <code>RpbGetBucketResp</code>
 */
class RpbGetBucketResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.RpbBucketProps props = 1;</code>
     */
    protected $props = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\RpbBucketProps $props
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\Riak::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.RpbBucketProps props = 1;</code>
     * @return \Basho\Riak\Api\Pb\Message\RpbBucketProps
     */
    public function getProps()
    {
        return isset($this->props) ? $this->props : null;
    }

    public function hasProps()
    {
        return isset($this->props);
    }

    public function clearProps()
    {
        unset($this->props);
    }

    /**
     * Generated from protobuf field <code>.RpbBucketProps props = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbBucketProps $var
     * @return $this
     */
    public function setProps($var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbBucketProps::class);
        $this->props = $var;

        return $this;
    }

}

