<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Get server info request - no message defined, just send RpbGetServerInfoReq message code
 *
 * Generated from protobuf message <code>RpbGetServerInfoResp</code>
 */
class RpbGetServerInfoResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes node = 1;</code>
     */
    protected $node = null;
    /**
     * Generated from protobuf field <code>bytes server_version = 2;</code>
     */
    protected $server_version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $node
     *     @type string $server_version
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\Riak::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes node = 1;</code>
     * @return string
     */
    public function getNode()
    {
        return isset($this->node) ? $this->node : '';
    }

    public function hasNode()
    {
        return isset($this->node);
    }

    public function clearNode()
    {
        unset($this->node);
    }

    /**
     * Generated from protobuf field <code>bytes node = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setNode($var)
    {
        GPBUtil::checkString($var, False);
        $this->node = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes server_version = 2;</code>
     * @return string
     */
    public function getServerVersion()
    {
        return isset($this->server_version) ? $this->server_version : '';
    }

    public function hasServerVersion()
    {
        return isset($this->server_version);
    }

    public function clearServerVersion()
    {
        unset($this->server_version);
    }

    /**
     * Generated from protobuf field <code>bytes server_version = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setServerVersion($var)
    {
        GPBUtil::checkString($var, False);
        $this->server_version = $var;

        return $this;
    }

}

