<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Get bucket-key preflist response
 *
 * Generated from protobuf message <code>RpbGetBucketKeyPreflistResp</code>
 */
class RpbGetBucketKeyPreflistResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .RpbBucketKeyPreflistItem preflist = 1;</code>
     */
    private $preflist;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\RpbBucketKeyPreflistItem[]|\Google\Protobuf\Internal\RepeatedField $preflist
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .RpbBucketKeyPreflistItem preflist = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPreflist()
    {
        return $this->preflist;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbBucketKeyPreflistItem preflist = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbBucketKeyPreflistItem[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPreflist($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbBucketKeyPreflistItem::class);
        $this->preflist = $arr;

        return $this;
    }

}

