<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Get Response - if the record was not found there will be no content/vclock
 *
 * Generated from protobuf message <code>RpbGetResp</code>
 */
class RpbGetResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .RpbContent content = 1;</code>
     */
    private $content;
    /**
     * the opaque vector clock for the object
     *
     * Generated from protobuf field <code>bytes vclock = 2;</code>
     */
    protected $vclock = null;
    /**
     * Generated from protobuf field <code>bool unchanged = 3;</code>
     */
    protected $unchanged = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\RpbContent[]|\Google\Protobuf\Internal\RepeatedField $content
     *     @type string $vclock
     *           the opaque vector clock for the object
     *     @type bool $unchanged
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .RpbContent content = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbContent content = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbContent[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContent($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbContent::class);
        $this->content = $arr;

        return $this;
    }

    /**
     * the opaque vector clock for the object
     *
     * Generated from protobuf field <code>bytes vclock = 2;</code>
     * @return string
     */
    public function getVclock()
    {
        return isset($this->vclock) ? $this->vclock : '';
    }

    public function hasVclock()
    {
        return isset($this->vclock);
    }

    public function clearVclock()
    {
        unset($this->vclock);
    }

    /**
     * the opaque vector clock for the object
     *
     * Generated from protobuf field <code>bytes vclock = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVclock($var)
    {
        GPBUtil::checkString($var, False);
        $this->vclock = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool unchanged = 3;</code>
     * @return bool
     */
    public function getUnchanged()
    {
        return isset($this->unchanged) ? $this->unchanged : false;
    }

    public function hasUnchanged()
    {
        return isset($this->unchanged);
    }

    public function clearUnchanged()
    {
        unset($this->unchanged);
    }

    /**
     * Generated from protobuf field <code>bool unchanged = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setUnchanged($var)
    {
        GPBUtil::checkBool($var);
        $this->unchanged = $var;

        return $this;
    }

}

