<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

if (false) {
    /**
     * This class is deprecated. Use Basho\Riak\Api\Pb\Message\RpbIndexReq\IndexQueryType instead.
     * @deprecated
     */
    class RpbIndexReq_IndexQueryType {}
}
class_exists(RpbIndexReq\IndexQueryType::class);
@trigger_error('Basho\Riak\Api\Pb\Message\RpbIndexReq_IndexQueryType is deprecated and will be removed in the next major release. Use Basho\Riak\Api\Pb\Message\RpbIndexReq\IndexQueryType instead', E_USER_DEPRECATED);

