<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Stolen from CS bucket response, to be used when return_body=true
 *
 * Generated from protobuf message <code>RpbIndexBodyResp</code>
 */
class RpbIndexBodyResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .RpbIndexObject objects = 1;</code>
     */
    private $objects;
    /**
     * Generated from protobuf field <code>bytes continuation = 2;</code>
     */
    protected $continuation = null;
    /**
     * Generated from protobuf field <code>bool done = 3;</code>
     */
    protected $done = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\RpbIndexObject[]|\Google\Protobuf\Internal\RepeatedField $objects
     *     @type string $continuation
     *     @type bool $done
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .RpbIndexObject objects = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getObjects()
    {
        return $this->objects;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbIndexObject objects = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbIndexObject[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setObjects($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbIndexObject::class);
        $this->objects = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes continuation = 2;</code>
     * @return string
     */
    public function getContinuation()
    {
        return isset($this->continuation) ? $this->continuation : '';
    }

    public function hasContinuation()
    {
        return isset($this->continuation);
    }

    public function clearContinuation()
    {
        unset($this->continuation);
    }

    /**
     * Generated from protobuf field <code>bytes continuation = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContinuation($var)
    {
        GPBUtil::checkString($var, False);
        $this->continuation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool done = 3;</code>
     * @return bool
     */
    public function getDone()
    {
        return isset($this->done) ? $this->done : false;
    }

    public function hasDone()
    {
        return isset($this->done);
    }

    public function clearDone()
    {
        unset($this->done);
    }

    /**
     * Generated from protobuf field <code>bool done = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;

        return $this;
    }

}

