<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Secondary Index query response
 *
 * Generated from protobuf message <code>RpbIndexResp</code>
 */
class RpbIndexResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes keys = 1;</code>
     */
    private $keys;
    /**
     * Generated from protobuf field <code>repeated .RpbPair results = 2;</code>
     */
    private $results;
    /**
     * Generated from protobuf field <code>bytes continuation = 3;</code>
     */
    protected $continuation = null;
    /**
     * Generated from protobuf field <code>bool done = 4;</code>
     */
    protected $done = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $keys
     *     @type \Basho\Riak\Api\Pb\Message\RpbPair[]|\Google\Protobuf\Internal\RepeatedField $results
     *     @type string $continuation
     *     @type bool $done
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes keys = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getKeys()
    {
        return $this->keys;
    }

    /**
     * Generated from protobuf field <code>repeated bytes keys = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setKeys($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->keys = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbPair results = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbPair results = 2;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbPair[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbPair::class);
        $this->results = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes continuation = 3;</code>
     * @return string
     */
    public function getContinuation()
    {
        return isset($this->continuation) ? $this->continuation : '';
    }

    public function hasContinuation()
    {
        return isset($this->continuation);
    }

    public function clearContinuation()
    {
        unset($this->continuation);
    }

    /**
     * Generated from protobuf field <code>bytes continuation = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setContinuation($var)
    {
        GPBUtil::checkString($var, False);
        $this->continuation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool done = 4;</code>
     * @return bool
     */
    public function getDone()
    {
        return isset($this->done) ? $this->done : false;
    }

    public function hasDone()
    {
        return isset($this->done);
    }

    public function clearDone()
    {
        unset($this->done);
    }

    /**
     * Generated from protobuf field <code>bool done = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;

        return $this;
    }

}

