<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Map/Reduce response
 * one or more of these packets will be sent the last one will have done set
 * true (and may not have phase/data in it)
 *
 * Generated from protobuf message <code>RpbMapRedResp</code>
 */
class RpbMapRedResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>uint32 phase = 1;</code>
     */
    protected $phase = null;
    /**
     * Generated from protobuf field <code>bytes response = 2;</code>
     */
    protected $response = null;
    /**
     * Generated from protobuf field <code>bool done = 3;</code>
     */
    protected $done = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $phase
     *     @type string $response
     *     @type bool $done
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint32 phase = 1;</code>
     * @return int
     */
    public function getPhase()
    {
        return isset($this->phase) ? $this->phase : 0;
    }

    public function hasPhase()
    {
        return isset($this->phase);
    }

    public function clearPhase()
    {
        unset($this->phase);
    }

    /**
     * Generated from protobuf field <code>uint32 phase = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setPhase($var)
    {
        GPBUtil::checkUint32($var);
        $this->phase = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes response = 2;</code>
     * @return string
     */
    public function getResponse()
    {
        return isset($this->response) ? $this->response : '';
    }

    public function hasResponse()
    {
        return isset($this->response);
    }

    public function clearResponse()
    {
        unset($this->response);
    }

    /**
     * Generated from protobuf field <code>bytes response = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setResponse($var)
    {
        GPBUtil::checkString($var, False);
        $this->response = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool done = 3;</code>
     * @return bool
     */
    public function getDone()
    {
        return isset($this->done) ? $this->done : false;
    }

    public function hasDone()
    {
        return isset($this->done);
    }

    public function clearDone()
    {
        unset($this->done);
    }

    /**
     * Generated from protobuf field <code>bool done = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;

        return $this;
    }

}

