<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Map/Reduce request
 *
 * Generated from protobuf message <code>RpbMapRedReq</code>
 */
class RpbMapRedReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes request = 1;</code>
     */
    protected $request = '';
    /**
     * Generated from protobuf field <code>bytes content_type = 2;</code>
     */
    protected $content_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $request
     *     @type string $content_type
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes request = 1;</code>
     * @return string
     */
    public function getRequest()
    {
        return $this->request;
    }

    /**
     * Generated from protobuf field <code>bytes request = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRequest($var)
    {
        GPBUtil::checkString($var, False);
        $this->request = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes content_type = 2;</code>
     * @return string
     */
    public function getContentType()
    {
        return $this->content_type;
    }

    /**
     * Generated from protobuf field <code>bytes content_type = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setContentType($var)
    {
        GPBUtil::checkString($var, False);
        $this->content_type = $var;

        return $this;
    }

}

