<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_kv.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Put response - same as get response with optional key if one was generated
 *
 * Generated from protobuf message <code>RpbPutResp</code>
 */
class RpbPutResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .RpbContent content = 1;</code>
     */
    private $content;
    /**
     * the opaque vector clock for the object
     *
     * Generated from protobuf field <code>bytes vclock = 2;</code>
     */
    protected $vclock = null;
    /**
     * the key generated, if any
     *
     * Generated from protobuf field <code>bytes key = 3;</code>
     */
    protected $key = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\RpbContent[]|\Google\Protobuf\Internal\RepeatedField $content
     *     @type string $vclock
     *           the opaque vector clock for the object
     *     @type string $key
     *           the key generated, if any
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakKv::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .RpbContent content = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbContent content = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbContent[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setContent($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbContent::class);
        $this->content = $arr;

        return $this;
    }

    /**
     * the opaque vector clock for the object
     *
     * Generated from protobuf field <code>bytes vclock = 2;</code>
     * @return string
     */
    public function getVclock()
    {
        return isset($this->vclock) ? $this->vclock : '';
    }

    public function hasVclock()
    {
        return isset($this->vclock);
    }

    public function clearVclock()
    {
        unset($this->vclock);
    }

    /**
     * the opaque vector clock for the object
     *
     * Generated from protobuf field <code>bytes vclock = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVclock($var)
    {
        GPBUtil::checkString($var, False);
        $this->vclock = $var;

        return $this;
    }

    /**
     * the key generated, if any
     *
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @return string
     */
    public function getKey()
    {
        return isset($this->key) ? $this->key : '';
    }

    public function hasKey()
    {
        return isset($this->key);
    }

    public function clearKey()
    {
        unset($this->key);
    }

    /**
     * the key generated, if any
     *
     * Generated from protobuf field <code>bytes key = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, False);
        $this->key = $var;

        return $this;
    }

}

