<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Set bucket properties request
 *
 * Generated from protobuf message <code>RpbSetBucketReq</code>
 */
class RpbSetBucketReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     */
    protected $bucket = '';
    /**
     * Generated from protobuf field <code>.RpbBucketProps props = 2;</code>
     */
    protected $props = null;
    /**
     * Generated from protobuf field <code>bytes type = 3;</code>
     */
    protected $type = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $bucket
     *     @type \Basho\Riak\Api\Pb\Message\RpbBucketProps $props
     *     @type string $type
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\Riak::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     * @return string
     */
    public function getBucket()
    {
        return $this->bucket;
    }

    /**
     * Generated from protobuf field <code>bytes bucket = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBucket($var)
    {
        GPBUtil::checkString($var, False);
        $this->bucket = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.RpbBucketProps props = 2;</code>
     * @return \Basho\Riak\Api\Pb\Message\RpbBucketProps
     */
    public function getProps()
    {
        return isset($this->props) ? $this->props : null;
    }

    public function hasProps()
    {
        return isset($this->props);
    }

    public function clearProps()
    {
        unset($this->props);
    }

    /**
     * Generated from protobuf field <code>.RpbBucketProps props = 2;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbBucketProps $var
     * @return $this
     */
    public function setProps($var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbBucketProps::class);
        $this->props = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes type = 3;</code>
     * @return string
     */
    public function getType()
    {
        return isset($this->type) ? $this->type : '';
    }

    public function hasType()
    {
        return isset($this->type);
    }

    public function clearType()
    {
        unset($this->type);
    }

    /**
     * Generated from protobuf field <code>bytes type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkString($var, False);
        $this->type = $var;

        return $this;
    }

}

