<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_search.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RpbSearchDoc</code>
 */
class RpbSearchDoc extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .RpbPair fields = 1;</code>
     */
    private $fields;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\RpbPair[]|\Google\Protobuf\Internal\RepeatedField $fields
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .RpbPair fields = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getFields()
    {
        return $this->fields;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbPair fields = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbPair[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setFields($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbPair::class);
        $this->fields = $arr;

        return $this;
    }

}

