<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_search.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RpbSearchQueryResp</code>
 */
class RpbSearchQueryResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Result documents
     *
     * Generated from protobuf field <code>repeated .RpbSearchDoc docs = 1;</code>
     */
    private $docs;
    /**
     * Maximum score
     *
     * Generated from protobuf field <code>float max_score = 2;</code>
     */
    protected $max_score = null;
    /**
     * Number of results
     *
     * Generated from protobuf field <code>uint32 num_found = 3;</code>
     */
    protected $num_found = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\RpbSearchDoc[]|\Google\Protobuf\Internal\RepeatedField $docs
     *           Result documents
     *     @type float $max_score
     *           Maximum score
     *     @type int $num_found
     *           Number of results
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakSearch::initOnce();
        parent::__construct($data);
    }

    /**
     * Result documents
     *
     * Generated from protobuf field <code>repeated .RpbSearchDoc docs = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDocs()
    {
        return $this->docs;
    }

    /**
     * Result documents
     *
     * Generated from protobuf field <code>repeated .RpbSearchDoc docs = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbSearchDoc[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDocs($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbSearchDoc::class);
        $this->docs = $arr;

        return $this;
    }

    /**
     * Maximum score
     *
     * Generated from protobuf field <code>float max_score = 2;</code>
     * @return float
     */
    public function getMaxScore()
    {
        return isset($this->max_score) ? $this->max_score : 0.0;
    }

    public function hasMaxScore()
    {
        return isset($this->max_score);
    }

    public function clearMaxScore()
    {
        unset($this->max_score);
    }

    /**
     * Maximum score
     *
     * Generated from protobuf field <code>float max_score = 2;</code>
     * @param float $var
     * @return $this
     */
    public function setMaxScore($var)
    {
        GPBUtil::checkFloat($var);
        $this->max_score = $var;

        return $this;
    }

    /**
     * Number of results
     *
     * Generated from protobuf field <code>uint32 num_found = 3;</code>
     * @return int
     */
    public function getNumFound()
    {
        return isset($this->num_found) ? $this->num_found : 0;
    }

    public function hasNumFound()
    {
        return isset($this->num_found);
    }

    public function clearNumFound()
    {
        unset($this->num_found);
    }

    /**
     * Number of results
     *
     * Generated from protobuf field <code>uint32 num_found = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNumFound($var)
    {
        GPBUtil::checkUint32($var);
        $this->num_found = $var;

        return $this;
    }

}

