<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_yokozuna.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RpbYokozunaIndexGetResp</code>
 */
class RpbYokozunaIndexGetResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .RpbYokozunaIndex index = 1;</code>
     */
    private $index;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\RpbYokozunaIndex[]|\Google\Protobuf\Internal\RepeatedField $index
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakYokozuna::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .RpbYokozunaIndex index = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIndex()
    {
        return $this->index;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbYokozunaIndex index = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbYokozunaIndex[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIndex($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbYokozunaIndex::class);
        $this->index = $arr;

        return $this;
    }

}

