<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_yokozuna.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RpbYokozunaIndex</code>
 */
class RpbYokozunaIndex extends \Google\Protobuf\Internal\Message
{
    /**
     * Index name
     *
     * Generated from protobuf field <code>bytes name = 1;</code>
     */
    protected $name = '';
    /**
     * Schema name
     *
     * Generated from protobuf field <code>bytes schema = 2;</code>
     */
    protected $schema = null;
    /**
     * N value
     *
     * Generated from protobuf field <code>uint32 n_val = 3;</code>
     */
    protected $n_val = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *           Index name
     *     @type string $schema
     *           Schema name
     *     @type int $n_val
     *           N value
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakYokozuna::initOnce();
        parent::__construct($data);
    }

    /**
     * Index name
     *
     * Generated from protobuf field <code>bytes name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Index name
     *
     * Generated from protobuf field <code>bytes name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, False);
        $this->name = $var;

        return $this;
    }

    /**
     * Schema name
     *
     * Generated from protobuf field <code>bytes schema = 2;</code>
     * @return string
     */
    public function getSchema()
    {
        return isset($this->schema) ? $this->schema : '';
    }

    public function hasSchema()
    {
        return isset($this->schema);
    }

    public function clearSchema()
    {
        unset($this->schema);
    }

    /**
     * Schema name
     *
     * Generated from protobuf field <code>bytes schema = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkString($var, False);
        $this->schema = $var;

        return $this;
    }

    /**
     * N value
     *
     * Generated from protobuf field <code>uint32 n_val = 3;</code>
     * @return int
     */
    public function getNVal()
    {
        return isset($this->n_val) ? $this->n_val : 0;
    }

    public function hasNVal()
    {
        return isset($this->n_val);
    }

    public function clearNVal()
    {
        unset($this->n_val);
    }

    /**
     * N value
     *
     * Generated from protobuf field <code>uint32 n_val = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setNVal($var)
    {
        GPBUtil::checkUint32($var);
        $this->n_val = $var;

        return $this;
    }

}

