<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_yokozuna.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RpbYokozunaSchemaGetResp</code>
 */
class RpbYokozunaSchemaGetResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.RpbYokozunaSchema schema = 1;</code>
     */
    protected $schema = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\RpbYokozunaSchema $schema
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakYokozuna::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.RpbYokozunaSchema schema = 1;</code>
     * @return \Basho\Riak\Api\Pb\Message\RpbYokozunaSchema
     */
    public function getSchema()
    {
        return isset($this->schema) ? $this->schema : null;
    }

    public function hasSchema()
    {
        return isset($this->schema);
    }

    public function clearSchema()
    {
        unset($this->schema);
    }

    /**
     * Generated from protobuf field <code>.RpbYokozunaSchema schema = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbYokozunaSchema $var
     * @return $this
     */
    public function setSchema($var)
    {
        GPBUtil::checkMessage($var, \Basho\Riak\Api\Pb\Message\RpbYokozunaSchema::class);
        $this->schema = $var;

        return $this;
    }

}

