<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_dt.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * An operation to update a Set, either on its own or inside a Map.
 * Set members are opaque binary values, you can only add or remove
 * them from a Set.
 *
 * Generated from protobuf message <code>SetOp</code>
 */
class SetOp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated bytes adds = 1;</code>
     */
    private $adds;
    /**
     * Generated from protobuf field <code>repeated bytes removes = 2;</code>
     */
    private $removes;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $adds
     *     @type string[]|\Google\Protobuf\Internal\RepeatedField $removes
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakDt::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated bytes adds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdds()
    {
        return $this->adds;
    }

    /**
     * Generated from protobuf field <code>repeated bytes adds = 1;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->adds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes removes = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRemoves()
    {
        return $this->removes;
    }

    /**
     * Generated from protobuf field <code>repeated bytes removes = 2;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRemoves($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->removes = $arr;

        return $this;
    }

}

