<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_ts.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TsCell</code>
 */
class TsCell extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes varchar_value = 1;</code>
     */
    protected $varchar_value = null;
    /**
     * Generated from protobuf field <code>sint64 sint64_value = 2;</code>
     */
    protected $sint64_value = null;
    /**
     * Generated from protobuf field <code>sint64 timestamp_value = 3;</code>
     */
    protected $timestamp_value = null;
    /**
     * Generated from protobuf field <code>bool boolean_value = 4;</code>
     */
    protected $boolean_value = null;
    /**
     * Generated from protobuf field <code>double double_value = 5;</code>
     */
    protected $double_value = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $varchar_value
     *     @type int|string $sint64_value
     *     @type int|string $timestamp_value
     *     @type bool $boolean_value
     *     @type float $double_value
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes varchar_value = 1;</code>
     * @return string
     */
    public function getVarcharValue()
    {
        return isset($this->varchar_value) ? $this->varchar_value : '';
    }

    public function hasVarcharValue()
    {
        return isset($this->varchar_value);
    }

    public function clearVarcharValue()
    {
        unset($this->varchar_value);
    }

    /**
     * Generated from protobuf field <code>bytes varchar_value = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setVarcharValue($var)
    {
        GPBUtil::checkString($var, False);
        $this->varchar_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 sint64_value = 2;</code>
     * @return int|string
     */
    public function getSint64Value()
    {
        return isset($this->sint64_value) ? $this->sint64_value : 0;
    }

    public function hasSint64Value()
    {
        return isset($this->sint64_value);
    }

    public function clearSint64Value()
    {
        unset($this->sint64_value);
    }

    /**
     * Generated from protobuf field <code>sint64 sint64_value = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSint64Value($var)
    {
        GPBUtil::checkInt64($var);
        $this->sint64_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint64 timestamp_value = 3;</code>
     * @return int|string
     */
    public function getTimestampValue()
    {
        return isset($this->timestamp_value) ? $this->timestamp_value : 0;
    }

    public function hasTimestampValue()
    {
        return isset($this->timestamp_value);
    }

    public function clearTimestampValue()
    {
        unset($this->timestamp_value);
    }

    /**
     * Generated from protobuf field <code>sint64 timestamp_value = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestampValue($var)
    {
        GPBUtil::checkInt64($var);
        $this->timestamp_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 4;</code>
     * @return bool
     */
    public function getBooleanValue()
    {
        return isset($this->boolean_value) ? $this->boolean_value : false;
    }

    public function hasBooleanValue()
    {
        return isset($this->boolean_value);
    }

    public function clearBooleanValue()
    {
        unset($this->boolean_value);
    }

    /**
     * Generated from protobuf field <code>bool boolean_value = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setBooleanValue($var)
    {
        GPBUtil::checkBool($var);
        $this->boolean_value = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>double double_value = 5;</code>
     * @return float
     */
    public function getDoubleValue()
    {
        return isset($this->double_value) ? $this->double_value : 0.0;
    }

    public function hasDoubleValue()
    {
        return isset($this->double_value);
    }

    public function clearDoubleValue()
    {
        unset($this->double_value);
    }

    /**
     * Generated from protobuf field <code>double double_value = 5;</code>
     * @param float $var
     * @return $this
     */
    public function setDoubleValue($var)
    {
        GPBUtil::checkDouble($var);
        $this->double_value = $var;

        return $this;
    }

}

