<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_ts.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TsInterpolation</code>
 */
class TsInterpolation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes base = 1;</code>
     */
    protected $base = '';
    /**
     * Generated from protobuf field <code>repeated .RpbPair interpolations = 2;</code>
     */
    private $interpolations;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $base
     *     @type \Basho\Riak\Api\Pb\Message\RpbPair[]|\Google\Protobuf\Internal\RepeatedField $interpolations
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes base = 1;</code>
     * @return string
     */
    public function getBase()
    {
        return $this->base;
    }

    /**
     * Generated from protobuf field <code>bytes base = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBase($var)
    {
        GPBUtil::checkString($var, False);
        $this->base = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbPair interpolations = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInterpolations()
    {
        return $this->interpolations;
    }

    /**
     * Generated from protobuf field <code>repeated .RpbPair interpolations = 2;</code>
     * @param \Basho\Riak\Api\Pb\Message\RpbPair[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInterpolations($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\RpbPair::class);
        $this->interpolations = $arr;

        return $this;
    }

}

