<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_ts.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TsPutReq</code>
 */
class TsPutReq extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes table = 1;</code>
     */
    protected $table = '';
    /**
     * optional: omitting it should use table order
     *
     * Generated from protobuf field <code>repeated .TsColumnDescription columns = 2;</code>
     */
    private $columns;
    /**
     * Generated from protobuf field <code>repeated .TsRow rows = 3;</code>
     */
    private $rows;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $table
     *     @type \Basho\Riak\Api\Pb\Message\TsColumnDescription[]|\Google\Protobuf\Internal\RepeatedField $columns
     *           optional: omitting it should use table order
     *     @type \Basho\Riak\Api\Pb\Message\TsRow[]|\Google\Protobuf\Internal\RepeatedField $rows
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes table = 1;</code>
     * @return string
     */
    public function getTable()
    {
        return $this->table;
    }

    /**
     * Generated from protobuf field <code>bytes table = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTable($var)
    {
        GPBUtil::checkString($var, False);
        $this->table = $var;

        return $this;
    }

    /**
     * optional: omitting it should use table order
     *
     * Generated from protobuf field <code>repeated .TsColumnDescription columns = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * optional: omitting it should use table order
     *
     * Generated from protobuf field <code>repeated .TsColumnDescription columns = 2;</code>
     * @param \Basho\Riak\Api\Pb\Message\TsColumnDescription[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsColumnDescription::class);
        $this->columns = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .TsRow rows = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRows()
    {
        return $this->rows;
    }

    /**
     * Generated from protobuf field <code>repeated .TsRow rows = 3;</code>
     * @param \Basho\Riak\Api\Pb\Message\TsRow[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsRow::class);
        $this->rows = $arr;

        return $this;
    }

}

