<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: riak_ts.proto

namespace Basho\Riak\Api\Pb\Message;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>TsQueryResp</code>
 */
class TsQueryResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .TsColumnDescription columns = 1;</code>
     */
    private $columns;
    /**
     * 0 to n rows
     *
     * Generated from protobuf field <code>repeated .TsRow rows = 2;</code>
     */
    private $rows;
    /**
     * Generated from protobuf field <code>bool done = 3;</code>
     */
    protected $done = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Basho\Riak\Api\Pb\Message\TsColumnDescription[]|\Google\Protobuf\Internal\RepeatedField $columns
     *     @type \Basho\Riak\Api\Pb\Message\TsRow[]|\Google\Protobuf\Internal\RepeatedField $rows
     *           0 to n rows
     *     @type bool $done
     * }
     */
    public function __construct($data = NULL) {
        \Basho\Riak\Api\Pb\Message\RiakTs::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .TsColumnDescription columns = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getColumns()
    {
        return $this->columns;
    }

    /**
     * Generated from protobuf field <code>repeated .TsColumnDescription columns = 1;</code>
     * @param \Basho\Riak\Api\Pb\Message\TsColumnDescription[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setColumns($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsColumnDescription::class);
        $this->columns = $arr;

        return $this;
    }

    /**
     * 0 to n rows
     *
     * Generated from protobuf field <code>repeated .TsRow rows = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRows()
    {
        return $this->rows;
    }

    /**
     * 0 to n rows
     *
     * Generated from protobuf field <code>repeated .TsRow rows = 2;</code>
     * @param \Basho\Riak\Api\Pb\Message\TsRow[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRows($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Basho\Riak\Api\Pb\Message\TsRow::class);
        $this->rows = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool done = 3;</code>
     * @return bool
     */
    public function getDone()
    {
        return isset($this->done) ? $this->done : false;
    }

    public function hasDone()
    {
        return isset($this->done);
    }

    public function clearDone()
    {
        unset($this->done);
    }

    /**
     * Generated from protobuf field <code>bool done = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setDone($var)
    {
        GPBUtil::checkBool($var);
        $this->done = $var;

        return $this;
    }

}

